function x = idct1d(dctx)
N = length(dctx);
Q= exp(pi*1i*((0:(N-1)))/(2*N));
Q(2:N)=Q(2:N)/sqrt(2/N);
dctxREO=dctx(N:(-1):2);
fy(1) = sqrt(N)*dctx(1); 
fy(2:N) =  Q(2:N).*(dctx(2:N)-1i*dctxREO);
y = real(ifft1d(fy));
x(1:2:(N-1)) = y(1:(N/2));
x(2:2:N) = y(N:(-1):(N/2+1));
