function trans = dct1d(x)
x = double(x);
N = length(x);
y = [x(1:2:(N-1)), x(N:(-2):2)];
fy = fft1d(y);
Refy = real(fy);
Imfy = imag(fy);
trans = sqrt(1/N)*(cos(pi*((0:(N-1))')/(2*N)).*Refy + sin(pi*((0:(N-1))')/(2*N)).*Imfy);
trans(2:N) =(trans(2:N)*sqrt(2));
trans = trans';
